### ISSUE TITLE
怎么安装使用呢

### ISSUE THREAD

**Issue by oo7typhk6j** [z2z63/VChat#1]
纯小白，求助各位大佬

**Comment by z2z63** [comment]
1. 准备一个虚拟环境（可选），要求python解释器版本不小于3.10（目前没有兼容到更低版本，未来会兼容）
2. 包已经上传[pypi](https://pypi.org/project/VChat/)，通过`pip install vchat`安装
3. 参考README中的最小工作实例，运行后扫码，完成登录过程，就能看到帐号给文件传输助手发送了hello, filehelper
4. 发送图片、视频、文件等功能请参考[message.py](https://github.com/z2z63/VChat/blob/master/vchat/core/messages.py)中的文档注释，后续也会增加文档
