### ISSUE TITLE
找不到QR.svg

### ISSUE THREAD

**Issue by yuandonghua** [z2z63/VChat#4]
![image](https://github.com/user-attachments/assets/629c5aac-fb03-4e29-bce0-a5a4e59271a8)
启动示例main.py提示找不到QR.svg,项目中有

**Comment by z2z63** [comment]
https://github.com/z2z63/VChat/blob/fd5697629cb84d736c7820149e9326fefc861b01/vchat/utils.py#L84-L85
在windows平台会使用explorer打开svg，需要注册表中有svg文件的正确打开方式，例如用图片查看器打开等  
从目录名猜测可能是项目结构不对，VChat-1.0.2也许是仓库release页面的源码压缩包，QR.svg默认会在python解释器的工作路径，一般也是项目根目录下
https://github.com/z2z63/VChat/blob/fd5697629cb84d736c7820149e9326fefc861b01/vchat/core/login.py#L68
https://github.com/z2z63/VChat/blob/fd5697629cb84d736c7820149e9326fefc861b01/vchat/config.py#L9

**Comment by yuandonghua** [comment]
![image](https://github.com/user-attachments/assets/f3cb3d09-5e2c-4dd5-998f-4590084ff075)

**Comment by yuandonghua** [comment]
![image](https://github.com/user-attachments/assets/cb4e15c7-cf3a-468c-abc2-fec9f9e65aa7)
需要设置一下svg打开方式

**Comment by z2z63** [comment]
explorer命令在文件扩展名关联的文件类型没有打开方式时，会报错“找不到应用程序”
start命令在此情况下则会弹窗引导用户选择一个程序打开svg文件

由于无法确定windows用户安装了那些图片查看器，所以只能使用windows系统自带的功能打开。如果遇到了此类问题，可以将`enable_cmd_qr`设为`True`，在终端打印图片

https://github.com/z2z63/VChat/blob/2bd804ca13aa076b6103db884d3a997e05c0465a/vchat/core/interface.py#L195-L203

此问题 在master中已经修复，暂时不发新版本，等待bugfix累计足够多后再发布

**Comment by z2z63** [comment]
已在v1.1.0 中修复
