### ISSUE TITLE
[FEATURE]希望发送图片的时候，能够添加一个传递字节流图片的参数，类似itchat

### ISSUE THREAD

**Issue by Waldo-Schaeffer** [z2z63/VChat#6]
![@NBG83QA@7UP3 Q05){4UBP](https://github.com/user-attachments/assets/519479d4-86ce-455d-b351-f07e11ad735b)
![UVA2(}K2KE2I9`PZTN5(9_0](https://github.com/user-attachments/assets/4587beb0-d1f8-4f8a-b9f3-32bc1e708f00)
对比所示，如果要做VCHATHTTP的话，字节流输入是不可避免的，也就是不使用fileDir而使用file_发送（类似使用剪切板粘贴一张内存中的图片发送）

**Comment by z2z63** [comment]
`fd`参数允许传入一个`ByteIO`对象，`ByteIO`对象可以通过以二进制模式打开一个文件产生，也可以利用内存中的`bytes`对象构造出来，参考 https://docs.python.org/3/library/io.html#binary-i-o
```python
f = open("myfile.jpg", "rb")
```
```
f = io.BytesIO(b"some initial binary data: \x00\x01")
```
