### ISSUE TITLE
[FEATURE]希望添加搜索功能

### ISSUE THREAD

**Issue by Waldo-Schaeffer** [z2z63/VChat#7]
希望能像itchat那样，使用search_friends、search_chatrooms、search_mps来搜索用户、群的username，以找到本次登录时的唯一id@@，方便定向发送信息

**Comment by Waldo-Schaeffer** [comment]
![图片](https://github.com/user-attachments/assets/a001aa38-4a35-4bcd-a5fa-234687f70877)

**Comment by z2z63** [comment]
提醒一点，nickname 是联系人自己设置的名称（好友给自己设置昵称，群主给群聊设置群名等），remarkName 是自己给联系人设置的备注
