### ISSUE TITLE
[BUG]在win2022服务器上，使用powershell运行时候，弹出二维码会报错

### ISSUE THREAD

**Issue by Waldo-Schaeffer** [z2z63/VChat#8]
修复方式：
将vchat/utils.py的函数修改成如下（改动部分已加粗显示）：
def print_qr(file_path):
    if config.OS == "linux":
        subprocess.call(["xdg-open", file_path])
    elif config.OS == "win32":
        subprocess.call(["start", file_path]**, shell=True**)
    elif config.OS == "darwin":
        subprocess.call(["open", file_path])
    else:
        raise NotImplementedError
即可。

**Comment by z2z63** [comment]
在 #9 中已经修复这个问题，已合入master，在v1.1.1发布
